---
# hostname (and path) to the root, e.g. http://spf13.com/
baseURL:                    "https://datasciencevision.com/"
# include content marked as draft
buildDrafts:                false
# include content with publishdate in the future
buildFuture:                false
# include content already expired
buildExpired:               false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs:               false
canonifyURLs:               false
# config file (default is path/config.yaml|json|toml)
config:                     "config.yaml"
contentDir:                 "content"
dataDir:                    "data"
defaultExtension:           "html"
defaultLayout:              "post"
# Missing translations will default to this content language
defaultContentLanguage:     "en-us"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: false
# Enable live reload
disableLiveReload:          false
# disable selectinve rendering
disableKinds:               ["RSS"]
# Enable GitInfo feature
enableGitInfo:              false
# Build robots.txt file
enableRobotsTXT:            false
# Do not inject generator meta tag on homepage
disableHugoGeneratorInject: false
# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji:                true
# disqus
disqusShortname:            "sadanandsblog"
# Show a placeholder instead of the default value or an empty string if a translation is missing
enableMissingTranslationPlaceholders: false
footnoteAnchorPrefix:       ""
footnoteReturnLinkContents: "↩"
# google analytics tracking id
googleAnalytics:            "UA-54080172-1"
languageCode:               "en-us"
layoutDir:                  "layouts"
# Enable Logging
log:                        false
# Log File path (if set, logging enabled automatically)
logFile:                    ""
# "yaml", "toml", "json"
metaDataFormat:             "yaml"
# Edit new content with this editor, if provided
newContentEditor:           ""
# Don't sync permission mode of files
noChmod:                    false
# Don't sync modification time of files
noTimes:                    false
paginate:                   8
paginatePath:               "page"
permalinks:
  post:  "/posts/:slug/"
# Pluralize titles in lists using inflect
pluralizeListTitles:        true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames:      false
# filesystem path to write files to
publishDir:                 "public"
# maximum number of items in the RSS feed
rssLimit:                   15
# default sitemap configuration map
sitemap:
# filesystem path to read files relative from
source:                     ""
staticDir:                  "static"
# display memory and timing of different steps of the program
stepAnalysis:               false
# taxanomies
taxonomies:
  tag:                      "tags"
  category:                 "categories"
  archive:                  "archives"
  author:                   "authors"
# theme to use (located by default in /themes/THEMENAME/)
themesDir:                  "themes"
theme:                      "bootstrap4"
title:                      "Sadanand's Notes"
# if true, use /filename.html instead of /filename/
uglyURLs:                   false
# Do not make the url/path to lowercase
disablePathToLower:         false
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage:             false
# verbose output
verbose:                    false
# verbose logging
verboseLog:                 false
# watch filesystem for changes and recreate as needed
watch:                      true

# Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
# they have to be referred from static root. Example
# customCSS = ["css/foo.css"]

# Custom JS. Put here your custom JS files. They are loaded after the theme JS;
# they have to be referred from static root. Example
# customJS = ["js/foo.js"]

# Output formats
outputs:
  home: [ "HTML", "JSON"]
  page: [ "HTML"]

# Menus in the top nav bar
menu:
  main:
    - Name: "Blog"
      Weight: 1
      Identifier: "blog"
      URL: "/post/"
    - Name: "Tags"
      Weight: 2
      Identifier: "tags"
      URL: "/tags/"
    - Name: "Categories"
      Weight: 3
      Identifier: "categories"
      URL: "/categories/"
    - Name: "Archive"
      Weight: 4
      Identifier: "archives"
      URL: "/archives/"

#Params
params:
  dateFormat:              "2006-01-02"
  hierarchicalcategories:  false
  fbAppId:                 "202188990663719"
  fb_api_version:          "v3.2"
  showTitle:               true
  bootswatch:              "cosmo"
  menubarColor:            "primary"
  # Use options from https://highlightjs.org/static/demo/
  highlightTheme:           "default"
  logoURL:                 "logo.png"
  socialButtonsCode:       "ra-53f6d74a591ace8f"
  license:                 '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>'

# Things that will be passed to CONTENT_FOOTER.format().  This is done
  favicons:
    - File: "apple-touch-icon.png"
      Size: "180x180"
      Name: "apple-touch-icon"
    - File: "favicon-32x32.png"
      Size: "32x32"
      Name: "icon"
    - File: "favicon-16x16.png"
      Size: "16x16"
      Name: "icon"

# Call to Action
  cta:
    enable: true
    title: "SO WHAT DO YOU THINK ?"
    content: "Would you like me to write on any particular topics in machine learning, deep learning? Do you like aything here or have any suggestions? Please leave me a note at any of the social links. You may also leave comments at any specific pages/posts."
    btnText: "Visit my Github Page"
    btnURL: "https://github.com/sadanand-singh"


# Author details
author:
  name:        "Sadanand Singh"
  # Your email used here only for copyright
  email:       "sadanand.singh@aol.com"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter:     "sadanandsingh"

imaging:
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter: "box"

  # Default JPEG quality setting. Default is 75.
  quality: 75

  # Anchor used when cropping pictures.
  # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
  # Smart Cropping is content aware and tries to find the best crop for each image.
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor: "smart"

---
